PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ncbitaxon:  <http://purl.obolibrary.org/obo/ncbitaxon#>

SELECT DISTINCT ?t ?l ?r ?parent
WHERE {
  ?t ?p ?v .
  VALUES ?t {obo:NCBITaxon_1804666 obo:NCBITaxon_3395531}
  ?t rdfs:label ?l .
  ?t rdfs:subClassOf ?parent .
  #?t ncbitaxon:has_rank ?r .
}