@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix obo:  <http://purl.obolibrary.org/obo/> .
@prefix ncbitaxon: <http://purl.obolibrary.org/obo/ncbitaxon#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix mb:  <http://kenshih.com/master-birder/ontology#> .

# Create the AvibaseID class and has_avibase_id predicate
mb:AvibaseID_1 rdf:type owl:Class ;
               rdfs:label "Avibase ID" .

mb:has_avibase_id rdf:type owl:ObjectProperty ;
                  rdfs:label "has avibase id" ;
                  rdfs:domain obo:NCBITaxon_1 ;
                  rdfs:range mb:AvibaseID_1 .