PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo:  <http://purl.obolibrary.org/obo/>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX mb:  <http://kenshih.com/master-birder/ontology#>

CONSTRUCT {
  ?avibaseInstance rdf:type mb:AvibaseIdentifier .
  ?avibaseInstance mb:identifierValue ?avibaseId .
  ?avibaseInstance rdfs:seeAlso ?avibaseUrl .
  ?avibaseInstance rdfs:label ?scientificName .
  ?avibaseInstance mb:has_avibase_id ?ncbiTaxon .
  ?ncbiTaxon rdf:type obo:NCBITaxon_1 .
  ?ncbiTaxon rdfs:label ?scientificName .
}
WHERE {
  # This would need to be replaced with your actual data source
  # For now, this is a template showing the structure
  
  BIND(IRI(CONCAT("http://kenshih.com/master-birder/ontology#AvibaseID_", ?avibaseId)) AS ?avibaseInstance)
  BIND(IRI(CONCAT("http://purl.obolibrary.org/obo/NCBITaxon_", ?ncbiTaxonId)) AS ?ncbiTaxon)
  BIND(CONCAT("https://avibase.bsc-eoc.org/species.jsp?avibaseid=", ?avibaseId) AS ?avibaseUrl)
  
  # Your data would come from a SERVICE or local data source
  # Example structure:
  # ?row :avibase_id ?avibaseId .
  # ?row :ncbi_taxon_id ?ncbiTaxonId .
  # ?row :scientific_name ?scientificName .
}
