PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mb: <http://kenshih.com/master-birder/ontology#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?aviLabel ?taxon ?aviId  ?avidb_link
WHERE {
  ?taxon mb:hasAvibaseIdentifier ?aviId .
  ?aviId rdfs:label ?aviLabel .  
  ?aviId rdfs:seeAlso ?avidb_link
}
